server:
  servlet:
    context-path: /rest
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
