# 日志配置
log:
  # 日志级别
  level:
    root: info
    com:
      fengfan:
        basis: debug
  file:
    path: ./log
    maxHistory: 20
    maxFileSize: 2KB
    totalSizeCap: 1GB
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n"
